config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'
  resources :contacts, except: :show
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_one_attached :picture

  validate :picture_attached
  validates_presence_of %w[firstname lastname telephone]

  def fullname
    "#{firstname} #{lastname}"
  end

  protected

  def picture_attached
    errors.add(:picture, "wasn't provided") unless picture.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :load_contact, only: %w[edit update destroy]

  def index
    @contacts = current_user.contacts.order(:firstname, :lastname)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.create(contact_params)
    if @contact.valid?
      flash[:notice] = "#{@contact.fullname} was saved."
      redirect_to contacts_path
    else
      render action: :new
    end
  end

  def edit; end

  def update
    @contact.update(contact_params)
    if @contact.valid?
      flash[:notice] = "#{@contact.fullname} was updated."
      redirect_to contacts_path
    else
      render action: :edit
    end
  end

  def destroy
    @contact.delete
    flash[:notice] = "#{@contact.fullname} was deleted."
    redirect_to contacts_path
  end

  protected

  def load_contact
    @contact = current_user.contacts.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(
      :picture,
      :firstname,
      :lastname,
      :telephone,
      :address
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/application/_message.html.erb
<div class="message <%= classes %>">
  <div class="message-body">
    <%= message %>
  </div>
</div>

app/views/contacts/_contact.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-96x96">
        <%= image_tag contact.picture %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p><strong><%= contact.fullname %></strong></p>
        <div>
          <span class="icon"><i class="fa fa-phone"></i></span>
          <span><%= contact.telephone %></span>
        </div>
        <% if contact.address.present? %>
          <div>
            <span class="icon"><i class="fa fa-home"></i></span>
            <span><%= contact.address %></span>
          </div>
        <% end %>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <a href="<%= edit_contact_path(contact) %>" class="icon is-small" title="Edit">
              <i class="fas fa-edit"></i>
            </a>
          </a>
          <a class="level-item">
            <%= link_to contact_path(contact), method: :delete, data: { confirm: 'You sure you want to delete this contact?' }, class: 'icon is-small' do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </a>
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <% @contact.errors.full_messages.each do |msg| %>
    <%= render partial: 'message', locals: { message: msg, classes: 'is-danger' } %>
  <% end %>
<% end %>

<%= form_for contact do |f| %>
  <div class="field">
    <label class="label">Picture *</label>
    <div class="control">
      <%= f.file_field :picture, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <label class="label">First name *</label>
    <div class="control">
      <%= f.text_field :firstname, class: 'input', placeholder: 'First name' %>
    </div>
  </div>

  <div class="field">
    <label class="label">Last name *</label>
    <div class="control">
      <%= f.text_field :lastname, class: 'input', placeholder: 'Last name' %>
    </div>
  </div>

  <div class="field">
    <label class="label">Telephone number *</label>
    <div class="control">
      <%= f.text_field :telephone, class: 'input', placeholder: 'Telephone number' %>
    </div>
  </div>

  <div class="field">
    <label class="label">Address</label>
    <div class="control">
      <%= f.text_field :address, class: 'input', placeholder: 'Address' %>
    </div>
  </div>

  <div class="field">
    <button class="button is-link" type="submit">Save</button>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1 class="title is-1">Edit <%= @contact.fullname %></h1>

<%= render partial: 'form', locals: { contact: @contact } %>

app/views/contacts/index.html.erb
<h1 class="title is-1">Contact list</h1>

<p>
  <%= link_to 'Add new contact', new_contact_path, class: 'button is-primary' %>
</p>

<% if @contacts.empty? %>
  <%= render partial: 'message', locals: { message: 'No contacts saved yet.', classes: 'is-success' } %>
<% else %>
  <% @contacts.each do |contact| %>
    <%= render partial: 'contact', locals: { contact: contact } %>
  <% end %>
<% end %>

app/views/contacts/new.html.erb
<h1 class="title is-1">Add new contact</h1>

<%= form_for @contact do |f| %>
  <div class="field">
    <label class="label">First name</label>
    <div class="control">
      <%= f.text_field :firstname, class: 'input', placeholder: 'First name' %>
    </div>
  </div>

  <div class="field">
    <label class="label">Last name</label>
    <div class="control">
      <%= f.text_field :lastname, class: 'input', placeholder: 'Last name' %>
    </div>
  </div>

  <div class="field">
    <label class="label">Telephone number</label>
    <div class="control">
      <%= f.text_field :telephone, class: 'input', placeholder: 'Telephone number' %>
    </div>
  </div>

  <div class="field">
    <label class="label">Address</label>
    <div class="control">
      <%= f.text_field :address, class: 'input', placeholder: 'Address' %>
    </div>
  </div>

  <div class="field">
    <button class="button is-link" type="submit">Save</button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-suppress-warning': true %>
  </head>

  <body>
    <main class="content container">
      <% if message = notice %>
        <%= render partial: 'message', locals: { message: message, classes: 'is-success' } %>
      <% end %>

      <% if message = alert %>
        <%= render partial: 'message', locals: { message: message, classes: 'is-danger' } %>
      <% end %>

      <%= yield %>
    </main>

    <footer class="footer">
      <section class="content has-text-centered">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        <% end %>
      </section>
    </footer>
  </body>
</html>